site_name: CKTu Lab Documents
site_url: https://alextu870719.github.io/MkDocs/

theme:
  name: material
  font:
    text: Inter
    code: JetBrains Mono
  logo: assets/wut.png
  favicon: assets/heyhey.ico
  features:
    - navigation.footer
  
  palette:  #Dark/Light Mode Toggle
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Dark mode
    primary: cyan
    accent: lime
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Light mode
    primary: indigo
    accent: amber

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: simple/youtube
      link: http://www.youtube.com/@杜紀寬
    - icon: simple/instagram
      link: https://www.instagram.com/chikuan0719/

copyright: Copyright &copy; 2025 Chi-Kuan Tu